"""tarifas: catalogos parametrizables y planes tarifarios

Revision ID: 0004_tarifas
Revises: 0003_rls
Create Date: 2026-08-26 00:26:36.059482
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '0004_tarifas'
down_revision: str | None = '0003_rls'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None



TABLAS_NUEVAS = ['vehicle_types', 'service_items', 'holidays', 'rate_plans', 'rate_rules', 'rate_tiers']
TENANT_ACTUAL = "NULLIF(current_setting('app.tenant_id', true), '')::uuid"


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('holidays',
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('nombre', sa.String(length=80), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'fecha', name='uq_holidays_tenant_fecha')
    )
    op.create_index(op.f('ix_holidays_fecha'), 'holidays', ['fecha'], unique=False)
    op.create_index(op.f('ix_holidays_tenant_id'), 'holidays', ['tenant_id'], unique=False)
    op.create_table('service_items',
    sa.Column('codigo', sa.String(length=32), nullable=False),
    sa.Column('nombre', sa.String(length=80), nullable=False),
    sa.Column('precio', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'codigo', name='uq_service_items_tenant_codigo')
    )
    op.create_index(op.f('ix_service_items_tenant_id'), 'service_items', ['tenant_id'], unique=False)
    op.create_table('vehicle_types',
    sa.Column('codigo', sa.String(length=32), nullable=False),
    sa.Column('nombre', sa.String(length=80), nullable=False),
    sa.Column('icono', sa.String(length=40), nullable=True),
    sa.Column('requiere_placa', sa.Boolean(), nullable=False),
    sa.Column('patron_placa', sa.String(length=120), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'codigo', name='uq_vehicle_types_tenant_codigo')
    )
    op.create_index(op.f('ix_vehicle_types_tenant_id'), 'vehicle_types', ['tenant_id'], unique=False)
    op.create_table('rate_plans',
    sa.Column('codigo', sa.String(length=32), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('parking_lot_id', sa.UUID(), nullable=True),
    sa.Column('estado', sa.Enum('borrador', 'activo', 'archivado', name='estadoplan', native_enum=False, create_constraint=True, length=16), nullable=False),
    sa.Column('vigente_desde', sa.Date(), nullable=True),
    sa.Column('vigente_hasta', sa.Date(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parking_lot_id'], ['parking_lots.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'codigo', 'version', name='uq_rate_plans_codigo_version')
    )
    op.create_index(op.f('ix_rate_plans_parking_lot_id'), 'rate_plans', ['parking_lot_id'], unique=False)
    op.create_index(op.f('ix_rate_plans_tenant_id'), 'rate_plans', ['tenant_id'], unique=False)
    op.create_table('rate_rules',
    sa.Column('rate_plan_id', sa.UUID(), nullable=False),
    sa.Column('vehicle_type_id', sa.UUID(), nullable=False),
    sa.Column('codigo', sa.String(length=48), nullable=False),
    sa.Column('modo', sa.Enum('por_minuto', 'por_bloque', 'primer_bloque_luego_minuto', 'escalonado', 'plena', 'por_dia', 'mensualidad', name='modocobro', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('precio_minuto', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('precio_bloque', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('precio_plena', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('precio_dia', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('bloque_minutos', sa.Integer(), nullable=False),
    sa.Column('dia_horas', sa.Integer(), nullable=False),
    sa.Column('gracia_minutos', sa.Integer(), nullable=False),
    sa.Column('cobro_minimo', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('tope_diario', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('tarifa_ticket_perdido', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('redondeo_modo', sa.Enum('arriba', 'abajo', 'cercano', name='modoredondeo', native_enum=False, create_constraint=True, length=16), nullable=False),
    sa.Column('redondeo_paso', sa.Integer(), nullable=False),
    sa.Column('impuesto_modo', sa.Enum('incluido', 'agregado', name='modoimpuesto', native_enum=False, create_constraint=True, length=16), nullable=False),
    sa.Column('impuesto_tasa', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('tiene_franja', sa.Boolean(), nullable=False),
    sa.Column('franja_dias', sa.ARRAY(sa.SmallInteger()), nullable=True),
    sa.Column('franja_desde', sa.Time(), nullable=True),
    sa.Column('franja_hasta', sa.Time(), nullable=True),
    sa.Column('franja_incluye_festivos', sa.Boolean(), nullable=False),
    sa.Column('franja_solo_festivos', sa.Boolean(), nullable=False),
    sa.Column('prioridad', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['rate_plan_id'], ['rate_plans.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vehicle_type_id'], ['vehicle_types.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rate_plan_id', 'codigo', name='uq_rate_rules_plan_codigo')
    )
    op.create_index(op.f('ix_rate_rules_rate_plan_id'), 'rate_rules', ['rate_plan_id'], unique=False)
    op.create_index(op.f('ix_rate_rules_tenant_id'), 'rate_rules', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_rate_rules_vehicle_type_id'), 'rate_rules', ['vehicle_type_id'], unique=False)
    op.create_table('rate_tiers',
    sa.Column('rate_rule_id', sa.UUID(), nullable=False),
    sa.Column('desde_minuto', sa.Integer(), nullable=False),
    sa.Column('hasta_minuto', sa.Integer(), nullable=True),
    sa.Column('precio', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('unidad', sa.Enum('fijo', 'bloque', 'minuto', name='unidadescalon', native_enum=False, create_constraint=True, length=16), nullable=False),
    sa.Column('bloque_minutos', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['rate_rule_id'], ['rate_rules.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rate_rule_id', 'desde_minuto', name='uq_rate_tiers_regla_desde')
    )
    op.create_index(op.f('ix_rate_tiers_rate_rule_id'), 'rate_tiers', ['rate_rule_id'], unique=False)
    op.create_index(op.f('ix_rate_tiers_tenant_id'), 'rate_tiers', ['tenant_id'], unique=False)
    # ### end Alembic commands ###



    # ── RLS para las tablas nuevas ──────────────────────────────────────
    # Mismo criterio que 0003_rls: filtrado por tenant_id y falla cerrado.
    # Los permisos del rol de aplicación los concede solo el
    # ALTER DEFAULT PRIVILEGES que dejó 0003.
    for tabla in TABLAS_NUEVAS:
        op.execute(f"ALTER TABLE {tabla} ENABLE ROW LEVEL SECURITY;")
        op.execute(f"""
            CREATE POLICY {tabla}_aislamiento ON {tabla}
            FOR ALL
            USING (tenant_id = {TENANT_ACTUAL})
            WITH CHECK (tenant_id = {TENANT_ACTUAL});
        """)


def downgrade() -> None:
    for tabla in TABLAS_NUEVAS:
        op.execute(f"DROP POLICY IF EXISTS {tabla}_aislamiento ON {tabla};")
        op.execute(f"ALTER TABLE {tabla} DISABLE ROW LEVEL SECURITY;")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rate_tiers_tenant_id'), table_name='rate_tiers')
    op.drop_index(op.f('ix_rate_tiers_rate_rule_id'), table_name='rate_tiers')
    op.drop_table('rate_tiers')
    op.drop_index(op.f('ix_rate_rules_vehicle_type_id'), table_name='rate_rules')
    op.drop_index(op.f('ix_rate_rules_tenant_id'), table_name='rate_rules')
    op.drop_index(op.f('ix_rate_rules_rate_plan_id'), table_name='rate_rules')
    op.drop_table('rate_rules')
    op.drop_index(op.f('ix_rate_plans_tenant_id'), table_name='rate_plans')
    op.drop_index(op.f('ix_rate_plans_parking_lot_id'), table_name='rate_plans')
    op.drop_table('rate_plans')
    op.drop_index(op.f('ix_vehicle_types_tenant_id'), table_name='vehicle_types')
    op.drop_table('vehicle_types')
    op.drop_index(op.f('ix_service_items_tenant_id'), table_name='service_items')
    op.drop_table('service_items')
    op.drop_index(op.f('ix_holidays_tenant_id'), table_name='holidays')
    op.drop_index(op.f('ix_holidays_fecha'), table_name='holidays')
    op.drop_table('holidays')
    # ### end Alembic commands ###
