"""operacion: tickets, cargos y pagos

Revision ID: 0005_operacion
Revises: 0004_tarifas
Create Date: 2026-08-26 01:14:32.113461
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '0005_operacion'
down_revision: str | None = '0004_tarifas'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None



TABLAS_NUEVAS = ['tickets', 'ticket_items', 'charges', 'payments']
TENANT_ACTUAL = "NULLIF(current_setting('app.tenant_id', true), '')::uuid"


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tickets',
    sa.Column('parking_lot_id', sa.UUID(), nullable=False),
    sa.Column('vehicle_type_id', sa.UUID(), nullable=False),
    sa.Column('numero', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=24), nullable=False),
    sa.Column('placa', sa.String(length=16), nullable=True),
    sa.Column('entrada_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('salida_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('estado', sa.Enum('abierto', 'cerrado', 'anulado', name='estadoticket', native_enum=False, create_constraint=True, length=16), nullable=False),
    sa.Column('operario_entrada_id', sa.UUID(), nullable=True),
    sa.Column('operario_salida_id', sa.UUID(), nullable=True),
    sa.Column('rate_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('observaciones', sa.String(length=300), nullable=True),
    sa.Column('anulacion_motivo', sa.String(length=300), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['operario_entrada_id'], ['memberships.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['operario_salida_id'], ['memberships.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['parking_lot_id'], ['parking_lots.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vehicle_type_id'], ['vehicle_types.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('parking_lot_id', 'numero', name='uq_tickets_sede_numero')
    )
    op.create_index('ix_tickets_busqueda', 'tickets', ['parking_lot_id', 'estado', 'placa'], unique=False)
    op.create_index(op.f('ix_tickets_codigo'), 'tickets', ['codigo'], unique=False)
    op.create_index(op.f('ix_tickets_estado'), 'tickets', ['estado'], unique=False)
    op.create_index(op.f('ix_tickets_parking_lot_id'), 'tickets', ['parking_lot_id'], unique=False)
    op.create_index(op.f('ix_tickets_placa'), 'tickets', ['placa'], unique=False)
    op.create_index(op.f('ix_tickets_tenant_id'), 'tickets', ['tenant_id'], unique=False)
    op.create_table('charges',
    sa.Column('ticket_id', sa.UUID(), nullable=False),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.Column('concepto', sa.String(length=120), nullable=False),
    sa.Column('detalle', sa.String(length=120), nullable=True),
    sa.Column('monto', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_charges_tenant_id'), 'charges', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_charges_ticket_id'), 'charges', ['ticket_id'], unique=False)
    op.create_table('payments',
    sa.Column('ticket_id', sa.UUID(), nullable=False),
    sa.Column('metodo', sa.Enum('efectivo', 'tarjeta', 'qr', 'transferencia', 'cortesia', name='metodopago', native_enum=False, create_constraint=True, length=16), nullable=False),
    sa.Column('monto', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('impuesto', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('recibido', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('cambio', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('referencia', sa.String(length=64), nullable=True),
    sa.Column('idempotency_key', sa.String(length=64), nullable=True),
    sa.Column('cash_shift_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'idempotency_key', name='uq_payments_idempotency')
    )
    op.create_index(op.f('ix_payments_tenant_id'), 'payments', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_payments_ticket_id'), 'payments', ['ticket_id'], unique=False)
    op.create_table('ticket_items',
    sa.Column('ticket_id', sa.UUID(), nullable=False),
    sa.Column('service_item_id', sa.UUID(), nullable=True),
    sa.Column('codigo', sa.String(length=32), nullable=False),
    sa.Column('nombre', sa.String(length=80), nullable=False),
    sa.Column('precio_unitario', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['service_item_id'], ['service_items.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ticket_items_tenant_id'), 'ticket_items', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_ticket_items_ticket_id'), 'ticket_items', ['ticket_id'], unique=False)
    # server_default para que las sedes que ya existen arranquen en cero;
    # el default se retira enseguida porque lo pone la aplicación.
    op.add_column(
        'parking_lots',
        sa.Column('ultimo_consecutivo', sa.Integer(), nullable=False, server_default='0'),
    )
    op.alter_column('parking_lots', 'ultimo_consecutivo', server_default=None)
    # ### end Alembic commands ###



    # RLS con el mismo criterio de 0003: filtrado por tenant_id, falla cerrado.
    for tabla in TABLAS_NUEVAS:
        op.execute(f"ALTER TABLE {tabla} ENABLE ROW LEVEL SECURITY;")
        op.execute(f"""
            CREATE POLICY {tabla}_aislamiento ON {tabla}
            FOR ALL
            USING (tenant_id = {TENANT_ACTUAL})
            WITH CHECK (tenant_id = {TENANT_ACTUAL});
        """)


def downgrade() -> None:
    for tabla in TABLAS_NUEVAS:
        op.execute(f"DROP POLICY IF EXISTS {tabla}_aislamiento ON {tabla};")
        op.execute(f"ALTER TABLE {tabla} DISABLE ROW LEVEL SECURITY;")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('parking_lots', 'ultimo_consecutivo')
    op.drop_index(op.f('ix_ticket_items_ticket_id'), table_name='ticket_items')
    op.drop_index(op.f('ix_ticket_items_tenant_id'), table_name='ticket_items')
    op.drop_table('ticket_items')
    op.drop_index(op.f('ix_payments_ticket_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_tenant_id'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_charges_ticket_id'), table_name='charges')
    op.drop_index(op.f('ix_charges_tenant_id'), table_name='charges')
    op.drop_table('charges')
    op.drop_index(op.f('ix_tickets_tenant_id'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_placa'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_parking_lot_id'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_estado'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_codigo'), table_name='tickets')
    op.drop_index('ix_tickets_busqueda', table_name='tickets')
    op.drop_table('tickets')
    # ### end Alembic commands ###
