"""caja: turnos y movimientos

Revision ID: 0006_caja
Revises: 0005_operacion
Create Date: 2026-08-26 01:52:06.877625
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '0006_caja'
down_revision: str | None = '0005_operacion'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None



TABLAS_NUEVAS = ["cash_shifts", "cash_movements"]
TENANT_ACTUAL = "NULLIF(current_setting('app.tenant_id', true), '')::uuid"


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cash_shifts',
    sa.Column('parking_lot_id', sa.UUID(), nullable=False),
    sa.Column('membership_id', sa.UUID(), nullable=False),
    sa.Column('abierto_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('cerrado_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('estado', sa.Enum('abierto', 'cerrado', name='estadoturno', native_enum=False, create_constraint=True, length=16), nullable=False),
    sa.Column('base_inicial', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('esperado', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('contado', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('diferencia', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('notas_apertura', sa.String(length=300), nullable=True),
    sa.Column('notas_cierre', sa.String(length=300), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['membership_id'], ['memberships.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['parking_lot_id'], ['parking_lots.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cash_shifts_estado'), 'cash_shifts', ['estado'], unique=False)
    op.create_index(op.f('ix_cash_shifts_membership_id'), 'cash_shifts', ['membership_id'], unique=False)
    op.create_index(op.f('ix_cash_shifts_parking_lot_id'), 'cash_shifts', ['parking_lot_id'], unique=False)
    op.create_index(op.f('ix_cash_shifts_tenant_id'), 'cash_shifts', ['tenant_id'], unique=False)
    op.create_table('cash_movements',
    sa.Column('cash_shift_id', sa.UUID(), nullable=False),
    sa.Column('membership_id', sa.UUID(), nullable=True),
    sa.Column('tipo', sa.Enum('ingreso', 'egreso', name='tipomovimiento', native_enum=False, create_constraint=True, length=16), nullable=False),
    sa.Column('concepto', sa.String(length=160), nullable=False),
    sa.Column('monto', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cash_shift_id'], ['cash_shifts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['membership_id'], ['memberships.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cash_movements_cash_shift_id'), 'cash_movements', ['cash_shift_id'], unique=False)
    op.create_index(op.f('ix_cash_movements_tenant_id'), 'cash_movements', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_payments_cash_shift_id'), 'payments', ['cash_shift_id'], unique=False)
    op.create_foreign_key(None, 'payments', 'cash_shifts', ['cash_shift_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###



    # Un operario no puede tener dos turnos abiertos en la misma sede. El
    # índice parcial lo impide en la base, no solo en el código: abrir dos
    # veces por un doble toque haría que el arqueo no cuadrara nunca.
    op.execute("""
        CREATE UNIQUE INDEX uq_turno_abierto_por_operario
        ON cash_shifts (parking_lot_id, membership_id)
        WHERE estado = 'abierto';
    """)

    for tabla in TABLAS_NUEVAS:
        op.execute(f"ALTER TABLE {tabla} ENABLE ROW LEVEL SECURITY;")
        op.execute(f"""
            CREATE POLICY {tabla}_aislamiento ON {tabla}
            FOR ALL
            USING (tenant_id = {TENANT_ACTUAL})
            WITH CHECK (tenant_id = {TENANT_ACTUAL});
        """)


def downgrade() -> None:
    op.execute("DROP INDEX IF EXISTS uq_turno_abierto_por_operario;")
    for tabla in TABLAS_NUEVAS:
        op.execute(f"DROP POLICY IF EXISTS {tabla}_aislamiento ON {tabla};")
        op.execute(f"ALTER TABLE {tabla} DISABLE ROW LEVEL SECURITY;")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'payments', type_='foreignkey')
    op.drop_index(op.f('ix_payments_cash_shift_id'), table_name='payments')
    op.drop_index(op.f('ix_cash_movements_tenant_id'), table_name='cash_movements')
    op.drop_index(op.f('ix_cash_movements_cash_shift_id'), table_name='cash_movements')
    op.drop_table('cash_movements')
    op.drop_index(op.f('ix_cash_shifts_tenant_id'), table_name='cash_shifts')
    op.drop_index(op.f('ix_cash_shifts_parking_lot_id'), table_name='cash_shifts')
    op.drop_index(op.f('ix_cash_shifts_membership_id'), table_name='cash_shifts')
    op.drop_index(op.f('ix_cash_shifts_estado'), table_name='cash_shifts')
    op.drop_table('cash_shifts')
    # ### end Alembic commands ###
